package readme

// TODO: Expand the README below by adding or modifying existing sections.
// TODO: Use your knowledge of the context of the code to determine what should be added or modified.
// TODO: You can create new sections and leave TODOs in them to be filled in by the AI.
// # readme.md
//
// # AGIBootstrap
//
// ![AGIBootstrap banner by DALL-E](docs/images/agib-dalle.jpg) AGIBootstrap is a self-bootstrapped artificial general intelligence (AGI) system designed for general coding tasks. The 'G' in AGI is often considered a humorous exaggeration due to the current limitations of AGI technology.
//
// > **Note:** This README is a work in progress. Our priority is to complete the code vector searching functionality, which will subsequently be used to automate the generation of this README file.
//
// ## Usage
//
// You can use AGIBootstrap by running the following command in your shell:
//
// ```shell
// # go run ./cmd/agib --help
// Usage:
//
//	go run ./cmd/agib [command]
//
// Available Commands:
//
//	commit      Commits the current staged changes with an automatically generated commit message.
//	completion  Generates the autocompletion script for the specified shell.
//	generate    Creates a new file.
//	help        Provides help about any command.
//	init        Initializes a new project.
//
// Flags:
//
//	-h, --help   Displays help for app.
//
// Use "app [command] --help" for more detailed information about a command.
// ```

// TODO: Add Origin section and explain the background and inspiration behind AGIBootstrap.

// TODO: Add How it works section and describe the functionality and components of the AGIBootstrap system.

// TODO: Add AI Safety section and provide guidelines and best practices for using AGIBootstrap responsibly.

// TODO: Add License section and specify the license under which AGIBootstrap is released.

func header() {}

// ## Origin
//
// AGIBootstrap was conceived as a single ChatGPT 4 prompt, written in pure markdown, that brainstormed its design. The first few lines of almost working code were generated by ChatGPT 3.5-4k. This version of ChatGPT read each `.go` file, searched for marker comments, used `gpt-3.5-turbo` (4k) to complete them, and then wrote the result back to the file.
//
// The original author and the AI collaboratively set up the system to automatically generate commit messages, commit changes, and push these changes, creating an infinite loop.
func origin() {}

// ## How it works
//
// The codex package is responsible for managing code generation and editing operations. It utilizes a state machine to keep track of the current state and allow for smooth transitions between different stages of the code generation process.
//
// The state machine consists of several states, such as 'idle,' 'editing,' and 'generating.' Each state has its own set of rules and conditions for transitioning to other states. For example, when the code generation process is initiated, the state transitions from 'idle' to 'generating,' and when the editing process is started, the state transitions to 'editing.' During the editing phase, users can make changes to the generated code, while in the generating phase, the AI agent generates new code based on predefined templates and user inputs.
//
// The codex package also provides functions for committing the generated code, managing version control, and handling other related tasks.
//
// This high-level overview should give you a better understanding of the codex package and its state machine.
//
// ### State machine diagram
//
// Below is a simplified diagram illustrating the different states and transitions in the codex package's state machine:
//
// TODO: Add state machine diagram (codegen, fiximport, fixbuild, commit, push, etc..)
//
// In the "Idle" state, the code generation process has not started. Once initiated, it transitions to the "Generating" state. From the "Generating" state, it can transition to the "Editing" state if the user wants to make changes to the generated code. From the "Editing" state, the user can save the changes and commit them, which transitions the state machine to the "Committing" state. Subsequently, further transitions can happen based on specific actions, such as sending a pull request or pulling the latest changes.
//
// This overview provides a high-level understanding of the codex package and its state machine. For more detailed information, refer to the package documentation and source code.
func howItWorks() {
	// TODO: Add state machine diagram (codegen, fiximport, fixbuild, commit, push, etc..)
	// TODO: Explain how the codex project Generate function works.
}

// ## AI Safety
//
// > **Work in progress:** This section is largely derived from the stable-diffusion-2.1 model card, with minor adjustments.
//
// AGIBootstrap is intended for research purposes only. It may be used in various fields such as:
//
// - Ensuring the safe deployment of models that could potentially generate harmful content.
// - Probing and understanding the limitations and biases of generative models.
// - Creating artworks and using them in design and other artistic processes.
// - Developing educational or creative tools.
// - Conducting research on generative models.
//
// Misuses, potential for malicious use, and out-of-scope uses are outlined below.
//
// ### Misuse, Malicious Use, and Out-of-Scope Use
//
// AGIBootstrap should not be used to intentionally create or distribute code that fosters a hostile environment or unsupervised code devoid of checks and balances.
//
// ### Out-of-Scope Use
//
// AGIBootstrap was not designed to create factual or accurate representations of people or events. Thus, using it to generate such content exceeds the model's capabilities and is considered out-of-scope.
//
// ### Misuse and Malicious Use
//
// The misuse of AGIBootstrap includes, but is not limited to:
//
// - Creating content that is demeaning, dehumanizing, or otherwise harmful to individuals or their environments, cultures, religions, etc.
// - Deliberately promoting or spreading discriminatory content or harmful stereotypes.
// - Impersonating individuals without their consent.
// - Generating sexual content without the consent of the potential audience.
// - Spreading misinformation or disinformation.
// - Representing extreme violence or gore.
// - Violating the terms of use of copyrighted or licensed material by sharing or modifying it.
//
// ## License
//
// AGIBootstrap is licensed under the AGPL license. For more information, please refer to the [LICENSE.md](LICENSE.md) file.
// TODO: Make this a world class design toc, be exhaustive in the topics you cover.
func init() {}
